countries = ['Australia',
                                                              'Botswana',
                                                              'Canada ',
                                                              'Ethiopia',
                                                              'Ghana',
                                                              'India ',
                                                              'Indonesia',
                                                              'Ireland',
                                                              'Israel ',
                                                              'Kenya',
                                                              'Latvia',
                                                              'Malaysia',
                                                              'Namibia',
                                                              'New Zealand',
                                                              'Nigeria',
                                                              'Pakistan',
                                                              'Philippines',
                                                              'Singapore',
                                                              'South Africa',
                                                              'Tanzania',
                                                              'Uganda',
                                                              'United Kingdom',
                                                              'United States',
                                                              'Zimbabwe',
                                                              'Czech Republic',
                                                              'Germany',
                                                              'Austria',
                                                              'Switzerland',
                                                              'Argentina',
                                                              'Chile',
                                                              'Colombia',
                                                              'Cuba',
                                                              'Mexico',
                                                              'Peru',
                                                              'Venezuela',
                                                              'Belgium ',
                                                              'France',
                                                              'Morocco',
                                                              'Senegal',
                                                              'Italy',
                                                              'Lithuania',
                                                              'Hungary',
                                                              'Netherlands',
                                                              'Norway',
                                                              'Poland',
                                                              'Brazil',
                                                              'Portugal',
                                                              'Romania',
                                                              'Slovakia',
                                                              'Slovenia',
                                                              'Sweden',
                                                              'Vietnam',
                                                              'Turkey',
                                                              'Greece',
                                                              'Bulgaria',
                                                              'Russia',
                                                              'Ukraine ',
                                                              'Serbia',
                                                              'United Arab Emirates',
                                                              'Saudi Arabia',
                                                              'Lebanon',
                                                              'Egypt',
                                                              'Bangladesh',
                                                              'Thailand',
                                                              'China',
                                                              'Taiwan',
                                                              'Hong Kong',
                                                              'Japan',
                                                              'Republic of Korea']
languages = ['english',
                                                         'indonesian',
                                                         'czech',
                                                         'german',
                                                         'spanish',
                                                         'french',
                                                         'italian',
                                                         'latvian',
                                                         'lithuanian',
                                                         'hungarian',
                                                         'dutch',
                                                         'norwegian',
                                                         'polish',
                                                         'portuguese brasil',
                                                         'portuguese portugal',
                                                         'romanian',
                                                         'slovak',
                                                         'slovenian',
                                                         'swedish',
                                                         'vietnamese',
                                                         'turkish',
                                                         'greek',
                                                         'bulgarian',
                                                         'russian',
                                                         'serbian',
                                                         'ukrainian',
                                                         'hebrew',
                                                         'arabic',
                                                         'marathi',
                                                         'hindi',
                                                         'bengali',
                                                         'tamil',
                                                         'telugu',
                                                         'malyalam',
                                                         'thai',
                                                         'chinese simplified',
                                                         'chinese traditional',
                                                         'japanese',
                                                         'korean']
topics = ['GENERAL', 'WORLD', 'NATION', 'BUSINESS', 'TECHNOLOGY', 'ENTERTAINMENT', 'SPORTS',
                                             'SCIENCE', 'HEALTH']

AVAILABLE_COUNTRIES = {'Australia': 'AU', 'Botswana': 'BW', 'Canada ': 'CA', 'Ethiopia': 'ET', 'Ghana': 'GH', 'India ': 'IN',
 'Indonesia': 'ID', 'Ireland': 'IE', 'Israel ': 'IL', 'Kenya': 'KE', 'Latvia': 'LV', 'Malaysia': 'MY', 'Namibia': 'NA',
 'New Zealand': 'NZ', 'Nigeria': 'NG', 'Pakistan': 'PK', 'Philippines': 'PH', 'Singapore': 'SG', 'South Africa': 'ZA',
 'Tanzania': 'TZ', 'Uganda': 'UG', 'United Kingdom': 'GB', 'United States': 'US', 'Zimbabwe': 'ZW',
 'Czech Republic': 'CZ', 'Germany': 'DE', 'Austria': 'AT', 'Switzerland': 'CH', 'Argentina': 'AR', 'Chile': 'CL',
 'Colombia': 'CO', 'Cuba': 'CU', 'Mexico': 'MX', 'Peru': 'PE', 'Venezuela': 'VE', 'Belgium ': 'BE', 'France': 'FR',
 'Morocco': 'MA', 'Senegal': 'SN', 'Italy': 'IT', 'Lithuania': 'LT', 'Hungary': 'HU', 'Netherlands': 'NL',
 'Norway': 'NO', 'Poland': 'PL', 'Brazil': 'BR', 'Portugal': 'PT', 'Romania': 'RO', 'Slovakia': 'SK', 'Slovenia': 'SI',
 'Sweden': 'SE', 'Vietnam': 'VN', 'Turkey': 'TR', 'Greece': 'GR', 'Bulgaria': 'BG', 'Russia': 'RU', 'Ukraine ': 'UA',
 'Serbia': 'RS', 'United Arab Emirates': 'AE', 'Saudi Arabia': 'SA', 'Lebanon': 'LB', 'Egypt': 'EG',
 'Bangladesh': 'BD', 'Thailand': 'TH', 'China': 'CN', 'Taiwan': 'TW', 'Hong Kong': 'HK', 'Japan': 'JP',
 'Republic of Korea': 'KR'}

AVAILABLE_LANGUAGES = {'english': 'en', 'indonesian': 'id', 'czech': 'cs', 'german': 'de', 'spanish': 'es-419', 'french': 'fr',
 'italian': 'it', 'latvian': 'lv', 'lithuanian': 'lt', 'hungarian': 'hu', 'dutch': 'nl', 'norwegian': 'no',
 'polish': 'pl', 'portuguese brasil': 'pt-419', 'portuguese portugal': 'pt-150', 'romanian': 'ro', 'slovak': 'sk',
 'slovenian': 'sl', 'swedish': 'sv', 'vietnamese': 'vi', 'turkish': 'tr', 'greek': 'el', 'bulgarian': 'bg',
 'russian': 'ru', 'serbian': 'sr', 'ukrainian': 'uk', 'hebrew': 'he', 'arabic': 'ar', 'marathi': 'mr', 'hindi': 'hi',
 'bengali': 'bn', 'tamil': 'ta', 'telugu': 'te', 'malyalam': 'ml', 'thai': 'th', 'chinese simplified': 'zh-Hans',
 'chinese traditional': 'zh-Hant', 'japanese': 'ja', 'korean': 'ko'}

suffixes = ('.jpg','.jpeg','.png','.JPG','.JPEG','.PNG')